# Generated by Django 3.2.3 on 2021-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Назва школи')),
                ('sc_manager', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Директор')),
                ('sc_address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адреса школи')),
                ('sc_site', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Сайт школи')),
                ('sc_phone', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер телефону')),
                ('sc_lat', models.FloatField(verbose_name='Широта')),
                ('sc_lon', models.FloatField(verbose_name='Довгота')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Назва університету')),
                ('un_manager', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Ректор')),
                ('un_address', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Адреса університету')),
                ('un_site', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Сайт університету')),
                ('un_phone', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Номер телефону')),
                ('un_lat', models.FloatField(verbose_name='Широта')),
                ('un_lon', models.FloatField(verbose_name='Довгота')),
            ],
        ),
    ]
